import { useRef, useState } from 'react'
import {
  ArrowLeft, ArrowRight, BellRing, BookOpen, Bot, Building2, CheckCircle2,
  ChevronRight, CircleAlert, Download, FileCheck2, FileText, Globe2, Landmark,
  Layers3, MonitorCheck, SearchCheck, ShieldCheck, Sparkles, UserRoundCheck,
} from 'lucide-react'
import { sources } from './data'
import type { SourceDocument, View } from './types'

type Navigate = (view: View) => void

export function LandingPage({ navigate, openSource }: { navigate: Navigate; openSource: (source: SourceDocument) => void }) {
  return <div className="public-page landing-page">
    <section className="landing-hero">
      <div className="landing-hero__copy">
        <span className="eyebrow">Regulatory Intelligence For Ethiopian Businesses</span>
        <h1>Know Which Rule Applies Before It Becomes A Filing Problem</h1>
        <p>Wayfinder monitors official regulatory sources, reconstructs what changed, and turns verified evidence into transaction-specific actions for service exporters, finance teams, and product builders.</p>
        <div className="hero-actions"><button className="button button--primary" onClick={() => navigate('login')}>Verify A Rule With Demo Access <ArrowRight /></button><button className="button button--secondary" onClick={() => navigate('pitch')}>View The Pitch Deck</button></div>
        <div className="landing-proof-line"><span><ShieldCheck /> Official Sources</span><span><Bot /> Active Monitoring Agent</span><span><UserRoundCheck /> Human Review Boundaries</span></div>
      </div>
      <div className="landing-hero__product" aria-label="Wayfinder product preview">
        <div className="preview-bar"><span /><span /><span /><small>Transaction Guidance</small></div>
        <div className="preview-body"><span className="status-badge status--verified"><CheckCircle2 /> Verified From Source</span><h2>100% Of Qualifying Service-Export Proceeds May Be Retained</h2><p>Matched to a service-export transaction received through a licensed Ethiopian bank.</p><div className="preview-evidence"><strong>Current Official Position</strong><span>Effective 11 Feb 2026</span><button onClick={() => openSource(sources[1])}>Inspect Official Evidence <ChevronRight /></button></div></div>
      </div>
    </section>

    <section className="narrative-section problem-section"><div className="narrative-heading"><span className="eyebrow">The Information Gap</span><h2>Authentic Information Can Still Produce The Wrong Decision</h2><p>Rules, amendments, notices, and explanations sit across different official pages and document formats. Older guidance often remains searchable after a newer publication changes the applicable position.</p></div><div className="problem-grid"><article><SearchCheck /><strong>Fragmented Discovery</strong><p>Teams search several regulator and ministry pages without knowing whether they found the latest rule.</p></article><article><CircleAlert /><strong>Version Confusion</strong><p>An authentic document can be outdated for a specific transaction, audience, or effective date.</p></article><article><FileText /><strong>Action Gap</strong><p>Finding a publication does not explain the next document, deadline, owner, or professional question.</p></article></div></section>

    <section className="narrative-section disparity-section"><div className="narrative-heading"><span className="eyebrow">A Real Regulatory Disparity</span><h2>Two Official Publications. Two Different Operational Conclusions.</h2></div><div className="disparity-flow"><article className="disparity-old"><small>Older Published Position</small><strong>50%</strong><p>of export proceeds shown as retained in foreign currency</p><span>2024 NBE FAQ</span></article><ArrowRight /><article className="disparity-current"><small>Current Service-Exporter Position</small><strong>100%</strong><p>of qualifying service-export proceeds may be retained</p><span>2026 NBE notice</span></article><div className="disparity-answer"><ShieldCheck /><strong>Wayfinder Reconstructs The Version Trail</strong><p>The product preserves both sources, identifies the applicable audience and date, and exposes the reasoning.</p></div></div></section>

    <section className="narrative-section workflow-section"><div className="narrative-heading"><span className="eyebrow">How Wayfinder Works</span><h2>From Official Publication To A Reviewable Action Plan</h2></div><ol className="workflow-steps"><li><span>01</span><MonitorCheck /><div><strong>Monitor Bounded Sources</strong><p>Wayfinder Watch scans administrator-approved regulator and ministry pages.</p></div></li><li><span>02</span><Layers3 /><div><strong>Detect And Structure Changes</strong><p>The agent fingerprints content and separates observed evidence from generated interpretation.</p></div></li><li><span>03</span><UserRoundCheck /><div><strong>Route Consequential Questions</strong><p>Conflicts and high-impact interpretations stop for curator or policy review.</p></div></li><li><span>04</span><FileCheck2 /><div><strong>Guide The Transaction</strong><p>The business receives a cited conclusion, checklist, evidence pack, and clear next steps.</p></div></li></ol></section>

    <section className="narrative-section outcomes-section"><div className="narrative-heading"><span className="eyebrow">What Users Gain</span><h2>Regulatory Awareness At The Moment A Business Decision Happens</h2></div><div className="outcome-grid"><article><strong>Current Rule</strong><p>A clear explanation of which publication applies to the stated transaction facts.</p></article><article><strong>Practical Checklist</strong><p>Ordered actions with owners, timing, required documents, and evidence.</p></article><article><strong>Traceable Confidence</strong><p>Authority, effective date, retrieval history, source relationship, and review status remain visible.</p></article><article><strong>Focused Expert Review</strong><p>Lawyers and policy professionals receive the exact unresolved question and linked evidence.</p></article></div></section>

    <section className="narrative-section audience-section"><div className="narrative-heading"><span className="eyebrow">Designed Around Trust Boundaries</span><h2>One Evidence Trail. A Purpose-Built Workspace For Every Role.</h2></div><div className="audience-grid"><article><Building2 /><strong>Business Owner</strong><p>Verifies the current rule before issuing an invoice or accepting foreign payment.</p></article><article><Landmark /><strong>Finance Lead</strong><p>Completes documentation, deadlines, and tax-file preparation tasks.</p></article><article><BookOpen /><strong>Source Curator</strong><p>Validates provenance, versions, amendments, and monitored changes.</p></article><article><UserRoundCheck /><strong>Policy Reviewer</strong><p>Resolves only conflicts and consequential interpretations.</p></article><article><Bot /><strong>Platform Administrator</strong><p>Configures the monitoring agent, sources, review rules, roles, and plans.</p></article></div></section>

    <section className="narrative-section scale-section"><div><span className="eyebrow">Built For Expansion</span><h2>Start Deep With Service Exports. Expand By Jurisdiction Pack.</h2><p>The proof of concept covers Ethiopia’s service-export, foreign-exchange, and adjacent tax-information workflow. The same evidence model can extend to goods exports, permits, public services, and additional African jurisdictions without removing local review boundaries.</p><button className="text-button" onClick={() => navigate('pitch')}>See The Product And Scale Model <ArrowRight /></button></div><Globe2 /></section>

    <section className="landing-cta"><Sparkles /><h2>Explore The Full Trust Workflow</h2><p>Enter as a business user, curator, reviewer, or platform administrator. Every demo identity is clearly labeled as synthetic.</p><div className="hero-actions"><button className="button button--primary" onClick={() => navigate('login')}>Choose A Demo Role <ArrowRight /></button><button className="button button--secondary" onClick={() => navigate('guide')}>Open The User Guide</button></div></section>
  </div>
}

const pitchSlides = [
  { kicker: 'OSF × Andela Hackathon', title: 'Wayfinder', subtitle: 'Evidence-Backed Regulatory Intelligence And Action For Ethiopian Businesses', type: 'cover' },
  { kicker: 'The Problem', title: 'Businesses Discover Regulatory Obligations Too Late', subtitle: 'Relevant information is fragmented across official pages, notices, directives, and scanned documents. Teams often investigate only when a bank, accountant, or filing deadline forces the question.', points: ['Older authentic guidance remains searchable', 'Applicability changes by date, audience, and transaction', 'A publication rarely explains the next operational step'] },
  { kicker: 'The User', title: 'Service Exporters Need Answers At The Transaction Moment', subtitle: 'The primary user is a founder or finance lead issuing an invoice or receiving foreign payment for digital services.', points: ['Confirm the current foreign-exchange position', 'Prepare the right evidence before tax filing', 'Escalate only the unresolved professional question'] },
  { kicker: 'The Evidence Gap', title: 'An Authentic Source May No Longer State The Current Position', subtitle: 'Wayfinder preserves the version trail instead of silently selecting one document.', metric: '50% → 100%', points: ['2024 FAQ showed a 50% retention position', '2026 notice identified a 100% position for service exporters', 'Audience and effective date determine applicability'] },
  { kicker: 'The Solution', title: 'Wayfinder Connects Evidence, Interpretation, Action, And Judgment', subtitle: 'The product separates four information layers so generated reasoning never appears to be official text.', points: ['Verified source evidence with dates and provenance', 'Generated interpretation with stated assumptions', 'Transaction-specific actions and evidence requirements', 'Recorded professional judgment for high-impact questions'] },
  { kicker: 'The Working Prototype', title: 'A Transaction Becomes A Cited Compliance Checklist', subtitle: 'A user describes the export transaction, confirms material facts, and receives the current position, required documents, deadlines, and an expert question package.', metric: '10 Min', points: ['Current-rule verification', 'Previous-versus-current comparison', 'Action checklist and evidence pack'] },
  { kicker: 'Autonomous Monitoring', title: 'Wayfinder Watch Detects Changes And Preserves Human Control', subtitle: 'The operational agent scans administrator-approved sources, fingerprints changes, structures candidate facts, and routes consequential interpretation to people.', points: ['Manual and scheduled live scans', 'Configurable official-source registry', 'Curator and policy-review queues', 'Timestamped run and decision history'] },
  { kicker: 'Trust And Safety', title: 'Consequential Guidance Cannot Publish Without The Required Review', subtitle: 'Foreign exchange, tax, filing, penalty, licensing, conflict, and probable supersession findings remain reviewable.', points: ['No unsupported confidence score', 'No unrestricted legal-advice chatbot', 'No silent conflict resolution', 'Synthetic fixtures remain clearly labeled'] },
  { kicker: 'Scale Model', title: 'Jurisdiction Packs Preserve Local Relevance While Supporting Expansion', subtitle: 'The service-export workflow provides the first deep vertical. Goods exports add customs, commodity, logistics, permit, tax, and foreign-exchange evidence.', points: ['Reusable evidence and review architecture', 'Local sources and professional reviewers', 'English-first interface with multilingual-ready content structures'] },
  { kicker: 'Build And Next Step', title: 'A Working Proof Of Concept Ready For Deeper Validation', subtitle: 'The prototype demonstrates the complete path from source monitoring to business action and professional review.', points: ['React and TypeScript frontend', 'Vercel Functions and scheduled scans', 'Supabase persistence', 'Structured AI extraction with deterministic fallback'], link: true },
]

export function PitchDeckView({ navigate }: { navigate: Navigate }) {
  const rail = useRef<HTMLDivElement>(null)
  const [active, setActive] = useState(0)
  function go(index: number) { const next = Math.max(0, Math.min(pitchSlides.length - 1, index)); setActive(next); rail.current?.children[next]?.scrollIntoView({ behavior: 'smooth', block: 'nearest', inline: 'start' }) }
  return <div className="pitch-page"><header className="pitch-page__header"><div><span className="eyebrow">Submission Pitch Deck</span><h1>Wayfinder Pitch Deck</h1><p>Use the controls or scroll horizontally through the slides.</p></div><div className="pitch-actions"><button className="button button--secondary" onClick={() => navigate('guide')}><BookOpen /> User Guide</button><a className="button button--primary" href="/wayfinder-pitch-deck.pdf" download><Download /> Download PDF</a></div></header><div className="pitch-stage"><div className="pitch-rail" ref={rail} onScroll={event => { const node = event.currentTarget; const next = Math.round(node.scrollLeft / Math.max(node.clientWidth, 1)); setActive(Math.max(0, Math.min(pitchSlides.length - 1, next))) }}>{pitchSlides.map((slide, index) => <article className={`pitch-slide pitch-slide--${slide.type ?? 'content'}`} key={slide.title} aria-label={`Slide ${index + 1}: ${slide.title}`}><div className="pitch-slide__number">{String(index + 1).padStart(2, '0')}</div><span className="pitch-slide__kicker">{slide.kicker}</span><h2>{slide.title}</h2><p className="pitch-slide__subtitle">{slide.subtitle}</p>{slide.metric && <strong className="pitch-slide__metric">{slide.metric}</strong>}{slide.points && <ul>{slide.points.map(point => <li key={point}><CheckCircle2 /> {point}</li>)}</ul>}{slide.link && <button className="pitch-guide-link" onClick={() => navigate('guide')}><BookOpen /> Open The Role-Based User Guide <ArrowRight /></button>}<div className="pitch-slide__brand">Wayfinder <span>Information You Can Trust And Act On</span></div></article>)}</div><div className="pitch-controls"><button aria-label="Previous slide" onClick={() => go(active - 1)} disabled={active === 0}><ArrowLeft /></button><span>Slide {active + 1} Of {pitchSlides.length}</span><button aria-label="Next slide" onClick={() => go(active + 1)} disabled={active === pitchSlides.length - 1}><ArrowRight /></button></div></div></div>
}

const roleGuides = [
  { id: 'owner', icon: Building2, role: 'Business Owner', goal: 'Confirm which rule applies before or after a foreign payment.', steps: ['Choose Business Owner on the demo sign-in page.', 'Open Verify A Rule and confirm the business and transaction facts.', 'Run Current-Rule Verification and inspect the official evidence.', 'Open Action Plans and review the evidence pack and expert questions.'], proves: 'Personalized, source-cited guidance and a safe boundary when evidence is incomplete.' },
  { id: 'finance', icon: Landmark, role: 'Finance Lead', goal: 'Translate the verified rule into documents, owners, and filing preparation.', steps: ['Choose Finance Lead.', 'Review the transaction profile and current position.', 'Complete checklist items and inspect their supporting sources.', 'Export or share the expert package before filing.'], proves: 'A practical path from regulatory information to accountable execution.' },
  { id: 'curator', icon: MonitorCheck, role: 'Source Curator', goal: 'Validate provenance and route candidate changes.', steps: ['Choose Source Curator.', 'Open Source Operations.', 'Review monitored findings or use manual, upload, and monitor ingestion demonstrations.', 'Validate evidence and route consequential changes to Policy Review.'], proves: 'Human validation between machine detection and regulatory interpretation.' },
  { id: 'reviewer', icon: UserRoundCheck, role: 'Policy Reviewer', goal: 'Resolve only conflicts and high-impact interpretations.', steps: ['Choose Policy Reviewer.', 'Open Review Queue.', 'Compare observed evidence with generated interpretation.', 'Record a scoped resolution or approve a monitored finding.'], proves: 'Professional judgment remains explicit, timestamped, and limited in scope.' },
  { id: 'admin', icon: Bot, role: 'Platform Administrator', goal: 'Operate Wayfinder Watch and govern access.', steps: ['Choose Platform Administrator.', 'Open Platform Overview.', 'Run a live scan or the clearly labeled controlled change demo.', 'Configure sources and review thresholds, then inspect System Audit.'], proves: 'Autonomous monitoring with bounded sources, visible status, and review controls.' },
]

export function UserGuideView({ navigate }: { navigate: Navigate }) {
  return <div className="guide-page"><header className="guide-hero"><div><span className="eyebrow">Wayfinder Demo Manual</span><h1>Role-Based User Guide</h1><p>Follow one role at a time to understand how evidence moves from source monitoring to business action and professional judgment.</p><button className="button button--primary" onClick={() => navigate('login')}>Choose A Demo Role <ArrowRight /></button></div><BookOpen /></header><nav className="guide-index" aria-label="User guide sections">{roleGuides.map(guide => <a href={`#guide-${guide.id}`} key={guide.id}>{guide.role}</a>)}</nav><section className="guide-orientation"><ShieldCheck /><div><h2>Before You Begin</h2><p>All named organizations, users, and transactions in the demo are synthetic. Official-source records retain their authority and links. Wayfinder provides decision support and does not replace qualified legal or tax advice.</p></div></section><div className="guide-roles">{roleGuides.map(({ id, icon: Icon, role, goal, steps, proves }) => <article id={`guide-${id}`} className="guide-role" key={id}><header><span><Icon /></span><div><small>Demo Role</small><h2>{role}</h2><p>{goal}</p></div></header><ol>{steps.map((step, index) => <li key={step}><span>{index + 1}</span><p>{step}</p></li>)}</ol><footer><strong>What This Workflow Demonstrates</strong><p>{proves}</p></footer></article>)}</div><section className="guide-demo-path"><BellRing /><div><span className="eyebrow">Recommended Judge Walkthrough</span><h2>A Seven-Minute End-To-End Path</h2><p>Start as Platform Administrator and run the controlled change demo. Route the finding to Policy Review. Switch to Policy Reviewer and approve it within scope. Then switch to Business Owner and verify the service-export transaction.</p></div><button className="button button--secondary" onClick={() => navigate('pitch')}>Return To Pitch Deck</button></section></div>
}
